spring.application.name=smartparking-backend
server.port=8080

# H2 en memoria para desarrollo (cambiar por MySQL/Postgres en produccion)
spring.datasource.url=jdbc:h2:mem:smartparking
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
